### ISSUE TITLE
Register bank numbers are not validated

### ISSUE THREAD

**Issue by serweryn617** [gembcior/d-ral#11]
Consider the following example:

```yaml
device:
  name: TEST_DEVICE
  description:
  peripherals:
  - name: PERIPHERAL
    description:
    address: 0x00
    registers:
    - name: TIM1
      description:
      offset: 0x00
      reset_value: 0x00
      fields: []
    - name: TIM3
      description:
      offset: 0x02
      reset_value: 0x00
      fields: []
```

The `TIM3` register will be accessible from C++ code as D-RAL register and from the register bank `TIMx`.

```cpp
peripheral::tim3::read();
// OR
peripheral::timx::read(3);  // Should this be 2 or 3? There is TIM0 in this example, but there could be
```

`TIMx` is defined as follows:

```cpp
using timx = TimxBankReg<BaseAddress + 0x0000, 0x0002>;
```

The offset, 0x0002, is calculated as the difference between `TIM3` and `TIM1`, which is incorrect.

Using `tim3::read()` will read from address 0x02, which is expected, but using `timx::read(3)` reads from address 0x06.
